name: 'Redis Release Version Action'
description: 'Composite GitHub action that sets and commits the given new version'
inputs:
  version:
    description: "The new version to set"
    required: true
runs:
  using: "composite"
  steps:
      - name: Set release version
        run: |
          VERSION=${{ inputs.version }}
          echo $VERSION > VERSION
          sed -i -e "s/^\:project-version\:\ .*/:project-version: $VERSION/g" README.adoc
          git add VERSION
          git add README.adoc
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git commit --allow-empty -a -m "Releasing version $VERSION"
          git push origin master
        shell: bash