name: 'Redis Version Action'
description: 'Composite GitHub action that commits and pushes the given new version of a project'
inputs:
  version:
    description: "The new version to set"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set release version
      run: |
        git add VERSION
        sed -i -e "s/^\:project-version\:\ .*/:project-version: ${{ inputs.version }}/g" README.adoc
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Action"
        git commit -a -m "Releasing version ${{ inputs.version }}"
        git push origin master
      shell: bash